name: DS340
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - matplotlib
  - numpy
  - pandas
  - pytest
  - pyyaml
  - scikit-learn
  - tqdm
  - pip:
      - torch>=2.6,<2.7
      - transformers>=4.45
